<?php

/**
 * PluginSetting.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id$
 */
abstract class PluginSetting extends BaseSetting {}
