<?php

/*
 * This file is part of the Symfony1 package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * PluginSettingTable.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PluginSettingTable extends \Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PluginSettingTable
     */
    public static function getInstance()
    {
        return \Doctrine_Core::getTable('PluginSetting');
    }
}
