version: '3.5'

volumes:
  db_socket:

services:
  php53: &services_php
    build:
      context: .docker/php53
      args:
        MEMCACHE_VERSION: '3.0.8'
        APC_VERSION: '3.1.13'
    working_dir: /app
    volumes:
      - .:/app
      - db_socket:/var/run/mysqld
    environment:
      COMPOSER_HOME: /app/var/cache/composer
      MEMCACHED_HOST: memcached
    entrypoint:
      - sh
      - -c
      - |
        {
          echo 'pdo_mysql.default_socket = /var/run/mysqld/mysql.sock'
          echo 'memory_limit = -1'
          echo 'short_open_tag = off'
          echo 'magic_quotes_gpc = off'
          echo 'date.timezone = "UTC"'
          echo 'apc.enable_cli = on'
          echo 'apc.use_request_time = off'
        } | tee -a /usr/local/etc/php/php.ini

        exec tail -f /dev/null
    depends_on:
      - db
      - memcached

  php54:
    <<: *services_php
    build:
      context: .docker/php54
      args:
        MEMCACHE_VERSION: '3.0.8'
        APC_VERSION: '3.1.13'

  php55:
    <<: *services_php
    build:
      context: .docker/php55_71
      args:
        PHP_TAG: '5.5-cli'
        MEMCACHE_VERSION: '3.0.8'
        APCU_VERSION: '4.0.11'

  php56:
    <<: *services_php
    build:
      context: .docker/php55_71
      args:
        PHP_TAG: '5.6-cli-jessie'
        MEMCACHE_VERSION: '3.0.8'
        APCU_VERSION: '4.0.11'

  php70:
    <<: *services_php
    build:
      context: .docker/php55_71
      args:
        PHP_TAG: '7.0-cli-jessie'
        MEMCACHE_VERSION: '4.0.5.2'
        APCU_VERSION: '5.1.23'

  php71:
    <<: *services_php
    build:
      context: .docker/php55_71
      args:
        PHP_TAG: '7.1-cli-jessie'
        MEMCACHE_VERSION: '4.0.5.2'
        APCU_VERSION: '5.1.23'

  php72:
    <<: *services_php
    build:
      context: .docker/php72_73
      args:
        PHP_VERSION: '7.2'
        MEMCACHE_VERSION: '4.0.5.2'
        APCU_VERSION: '5.1.23'

  php73:
    <<: *services_php
    build:
      context: .docker/php72_73
      args:
        PHP_VERSION: '7.3'
        MEMCACHE_VERSION: '4.0.5.2'
        APCU_VERSION: '5.1.23'

  php74:
    <<: *services_php
    build:
      context: .docker/php74_83
      args:
        PHP_VERSION: '7.4'
        MEMCACHE_VERSION: '4.0.5.2'
        APCU_VERSION: '5.1.23'

  php80:
    <<: *services_php
    build:
      context: .docker/php74_83
      args:
        PHP_VERSION: '8.0'
        MEMCACHE_VERSION: '8.0'
        APCU_VERSION: '5.1.23'

  php81:
    <<: *services_php
    build:
      context: .docker/php74_83
      args:
        PHP_VERSION: '8.1'
        MEMCACHE_VERSION: '8.0'
        APCU_VERSION: '5.1.23'

  php82:
    <<: *services_php
    build:
      context: .docker/php74_83
      args:
        PHP_VERSION: '8.2'
        MEMCACHE_VERSION: '8.0'
        APCU_VERSION: '5.1.23'

  php83:
    <<: *services_php
    build:
      context: .docker/php74_83
      args:
        PHP_VERSION: '8.3'
        MEMCACHE_VERSION: '8.0'
        APCU_VERSION: '5.1.23'


  db:
    image: mysql:5.5.62
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - db_socket:/tmp
    entrypoint:
      - bash
      - -c
      - |
        {
            echo "CREATE DATABASE IF NOT EXISTS test;"
        } | tee /docker-entrypoint-initdb.d/init.sql

        exec /usr/local/bin/docker-entrypoint.sh mysqld

  memcached:
    image: memcached:1.6.13-alpine3.15
