<?php

/**
 * AuthorInheritance.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 */
class AuthorInheritance extends BaseAuthorInheritance
{
}
