<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework.
 */
class AuthorTable extends Doctrine_Table
{
    public function testTableMethod()
    {
        return $this->createQuery('a')
            ->where('a.id > 0')
        ;
    }

    public function testTableMethod2(Doctrine_Query $q)
    {
        $q->addWhere('a.id > 0');

        return $q;
    }

    public function getChoices($limit = null)
    {
        $q = $this->createQuery('a');
        if (null !== $limit) {
            $q->limit($limit);
        }
        $choices = [];

        foreach ($q->fetchArray() as $author) {
            $choices[$author['id']] = $author['name'];
        }

        return $choices;
    }
}
