<?php

/**
 * AuthorInheritance.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id$
 */
class AuthorInheritance extends BaseAuthorInheritance {}
