<?php

/**
 * AuthorInheritanceConcrete.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 */
class AuthorInheritanceConcrete extends BaseAuthorInheritanceConcrete
{
}
