<?php

/**
 * BlogArticle.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     Your name here
 *
 * @version    SVN: $Id$
 */
class BlogArticle extends BaseBlogArticle {}
