<?php

/**
 * BlogAuthor.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     Your name here
 *
 * @version    SVN: $Id$
 */
class BlogAuthor extends BaseBlogAuthor {}
