<?php

/**
 * CamelCase.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id$
 */
class CamelCase extends BaseCamelCase {}
