<?php

/**
 * DefaultValueTest.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @internal
 *
 * @coversNothing
 */
class DefaultValueTest extends BaseDefaultValueTest
{
}
