<?php

/**
 * FormGeneratorTest.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @internal
 *
 * @coversNothing
 */
class FormGeneratorTest extends BaseFormGeneratorTest
{
}
