<?php

/**
 * FormGeneratorTest2.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     ##NAME## <##EMAIL##>
 *
 * @version    SVN: $Id$
 */
class FormGeneratorTest2 extends BaseFormGeneratorTest2 {}
