<?php

/**
 * FormGeneratorTest3.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     Your name here
 */
class FormGeneratorTest3 extends BaseFormGeneratorTest3
{
}
