<?php

/**
 * FormGeneratorTest3.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     Your name here
 *
 * @version    SVN: $Id: Builder.php 6716 2009-11-12 19:26:28Z jwage $
 */
class FormGeneratorTest3 extends BaseFormGeneratorTest3 {}
