<?php

/**
 * ModelFromLinkedSchema.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     Your name here
 */
class ModelFromLinkedSchema extends BaseModelFromLinkedSchema
{
}
