<?php

/**
 * ModelWithNumberInColumn.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     Your name here
 */
class ModelWithNumberInColumn extends BaseModelWithNumberInColumn
{
}
