<?php

/*
 * This file is part of the Symfony1 package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * ModelWithNumberInColumn.
 *
 * This class has been auto-generated by the Doctrine ORM Framework
 *
 * @author     Your name here
 *
 * @version    SVN: $Id: Builder.php 6820 2009-11-30 17:27:49Z jwage $
 */
class ModelWithNumberInColumn extends \BaseModelWithNumberInColumn
{
}
