<?php

/*
 * This file is part of the Symfony1 package.
 *
 * (c) Fabien Potencier <fabien@symfony.com>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

/**
 * This class has been auto-generated by the Doctrine ORM Framework.
 */
class ProfileTable extends \Doctrine_Table
{
}
