name: "Code Linting"
on:
  push:
    paths:
      - .php-cs-fixer.dist.php
      - autoload.php
      - lib/**
      - data/**
      - tests/**
    branches:
      - master
  pull_request:
    paths:
      - .php-cs-fixer.dist.php
      - autoload.php
      - lib/**
      - data/**
      - tests/**

jobs:
  php-cs-fixer:
    name: 'PHP-CS-Fixer'
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.4
          tools: php-cs-fixer:3.52, cs2pr

      - uses: actions/cache@v4
        with:
          path: '.php-cs-fixer.cache'
          key: ${{ github.repository }}-7.4-phpcsfixer-${{ github.ref_name }}
          restore-keys: |
            ${{ github.repository }}-7.4-phpcsfixer-master
            ${{ github.repository }}-7.4-phpcsfixer-

      - name: Run PHP-CS-Fixer
        # Using cs2pr settings, see: https://github.com/shivammathur/setup-php#tools-with-checkstyle-support
        run: 'php-cs-fixer fix --dry-run --format=checkstyle | cs2pr'
